version: "3.8"

services:
  config-service:
    image: 721431533455.dkr.ecr.ap-southeast-2.amazonaws.com/config-service:${CONFIG_SERVICE_IMAGE}
    platform: linux/amd64
    container_name: config-service
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ap-southeast-2
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  catalog-service:
    image: 721431533455.dkr.ecr.ap-southeast-2.amazonaws.com/catalog-service:${CATALOG_SERVICE_IMAGE}
    platform: linux/amd64
    container_name: catalog-service
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - app-network

  demo-service:
    image: 721431533455.dkr.ecr.ap-southeast-2.amazonaws.com/demo-service:${DEMO_SERVICE_IMAGE}
    platform: linux/amd64
    container_name: demo-service
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
    ports:
      - "9090:8080"
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port for Spring Cloud Bus
      - "15672:15672"  # Management UI port for inspection
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
